# Generated by Django 3.2.16 on 2024-09-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240905_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(help_text='Если установить дату и время в будущем — можно делатьотложенные публикации.', verbose_name='Дата и время публикации'),
        ),
    ]
