# Generated by Django 3.2.16 on 2024-09-09 18:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20240909_2055'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('post_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Категория'),
        ),
    ]
